apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-04-11T07:15:00Z"
  generation: 1
  labels:
    app: odoo
  name: odoo
  namespace: default
  resourceVersion: "7324"
  uid: 87f03839-383a-49eb-97fb-46af733ccf37
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: odoo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: odoo
    spec:
      containers:
      - image: asia-southeast1-docker.pkg.dev/odoo-lab-vsi/bidv-poc/bidv_poc@sha256:de60868d544b97b3ccf2effaecb287a084af7a7ffb2ae90a18be1f0261700403
        imagePullPolicy: IfNotPresent
        name: bidv-poc-sha256-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - command:
        - bash
        image: asia-southeast1-docker.pkg.dev/odoo-lab-vsi/bidv-poc/bidv_poc@sha256:de60868d544b97b3ccf2effaecb287a084af7a7ffb2ae90a18be1f0261700403
        imagePullPolicy: IfNotPresent
        name: bidv-poc-sha256-2
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30